/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControllerArquivoTextoCircuito;
import Model.Circuito;
import javax.swing.JOptionPane;

/**
 *
 * @author luizg
 */
public class VwCircuito extends javax.swing.JFrame {

    int index = 0;
    ControllerArquivoTextoCircuito ctrl = new ControllerArquivoTextoCircuito();

    /**
     * Creates new form VwCircuito
     */
    public VwCircuito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPista = new javax.swing.JLabel();
        jLabelPais = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jLabelExt = new javax.swing.JLabel();
        jLabelVoltas = new javax.swing.JLabel();
        jLabelRcrd = new javax.swing.JLabel();
        jTextFieldPista = new javax.swing.JTextField();
        jTextFieldPais = new javax.swing.JTextField();
        jTextFieldCidade = new javax.swing.JTextField();
        jTextFieldExt = new javax.swing.JTextField();
        jTextFieldVoltas = new javax.swing.JTextField();
        jTextFieldRcrd = new javax.swing.JTextField();
        jLabelTitle = new javax.swing.JLabel();
        jLabelKm = new javax.swing.JLabel();
        jButtonAbrir = new javax.swing.JButton();
        jButtonAnt = new javax.swing.JButton();
        jButtonProx = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jTextFieldId = new javax.swing.JTextField();
        jButtonBusca = new javax.swing.JButton();
        jLabelId = new javax.swing.JLabel();
        jButtonDel = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Circuito");

        jLabelPista.setText("Nome do Circuito:");

        jLabelPais.setText("País:");

        jLabelCidade.setText("Cidade:");

        jLabelExt.setText("Extensão:");

        jLabelVoltas.setText("Número de Voltas:");

        jLabelRcrd.setText("Tempo Record:");

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitle.setText("CIRCUITO");

        jLabelKm.setText("Km.");

        jButtonAbrir.setText("Abrir");
        jButtonAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAbrirMouseClicked(evt);
            }
        });

        jButtonAnt.setText("Anterior");
        jButtonAnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAntMouseClicked(evt);
            }
        });

        jButtonProx.setText("Próximo");
        jButtonProx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonProxMouseClicked(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalvarMouseClicked(evt);
            }
        });

        jTextFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdActionPerformed(evt);
            }
        });

        jButtonBusca.setText("Buscar por Id");
        jButtonBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBuscaMouseClicked(evt);
            }
        });

        jLabelId.setText("Id:");

        jButtonDel.setText("Deletar por Id");
        jButtonDel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDelMouseClicked(evt);
            }
        });

        jButtonEdit.setText("Editar por Id");
        jButtonEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEditMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelRcrd)
                                        .addComponent(jLabelPais)
                                        .addComponent(jLabelCidade)
                                        .addComponent(jLabelExt)
                                        .addComponent(jLabelVoltas))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldPais)
                                        .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextFieldExt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabelKm))
                                        .addComponent(jTextFieldVoltas, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldRcrd, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelPista)
                                        .addComponent(jLabelId))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldPista))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAbrir)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAnt)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonProx)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSalvar)))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonEdit)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDel)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBusca)
                        .addGap(23, 23, 23))))
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabelTitle)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelId))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPista, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldPista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPais)
                    .addComponent(jTextFieldPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCidade, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldExt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelExt)
                    .addComponent(jLabelKm))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVoltas)
                    .addComponent(jTextFieldVoltas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRcrd)
                    .addComponent(jTextFieldRcrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEdit)
                    .addComponent(jButtonDel)
                    .addComponent(jButtonBusca))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAbrir)
                    .addComponent(jButtonAnt)
                    .addComponent(jButtonProx)
                    .addComponent(jButtonSalvar))
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalvarMouseClicked
        // TODO add your handling code here:
        ctrl.setArquivo("Salvar");
        Circuito circuito = new Circuito();
        circuito.setPista(jTextFieldPista.getText());
        circuito.setPais(jTextFieldPais.getText());
        circuito.setCidade(jTextFieldCidade.getText());
        circuito.setExtensao(Integer.parseInt(jTextFieldExt.getText()));
        circuito.setVoltas(Integer.parseInt(jTextFieldVoltas.getText()));
        circuito.setRecord(jTextFieldRcrd.getText());
        ctrl.getCircuitos().add(circuito);
        ctrl.escreverCircuito(true);
    }//GEN-LAST:event_jButtonSalvarMouseClicked

    private void jButtonAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAbrirMouseClicked
        // TODO add your handling code here:
        ctrl.setArquivo("Abrir");
        ctrl.lerCircuito();
        index = 0;
        Nav(index);
        System.out.println("index inicializado em: " + index);
    }//GEN-LAST:event_jButtonAbrirMouseClicked

    private void jButtonProxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonProxMouseClicked
        // TODO add your handling code here:
        System.out.println("tamanho do array: " + ctrl.getCircuitos().size());
        while (this.isActive()) {
            try {
                if (index <= ctrl.getCircuitos().size() - 1) {
                    Nav(++index);
                    System.out.println("index atual = " + index);
                    break;
                } else {
                    JOptionPane.showMessageDialog(this, "Não há mais circuitos cadastrados.");
                    break;
                }
            } catch (IndexOutOfBoundsException erro) {
                JOptionPane.showMessageDialog(this, "Ocorreu um erro ao acessar o circuito.");
                break;
            }
        }
    }//GEN-LAST:event_jButtonProxMouseClicked

    private void jButtonAntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAntMouseClicked
        // TODO add your handling code here:
        while (this.isActive()) {
            try {
                if (index >= 0) {
                    Nav(--index);
                    System.out.println("index atual = " + index);
                    break;
                } else {
                    JOptionPane.showMessageDialog(this, "Não há mais circuitos cadastrados.");
                    break;
                }
            } catch (IndexOutOfBoundsException erro) {
                JOptionPane.showMessageDialog(this, "Ocorreu um erro ao acessar o circuito.");
                break;
            }
        }
        //Nav(--index);
    }//GEN-LAST:event_jButtonAntMouseClicked

    private void jTextFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdActionPerformed

    private void jButtonBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscaMouseClicked
        // TODO add your handling code here:
        int aux = Integer.parseInt(jTextFieldId.getText());
        Buscar(aux);
    }//GEN-LAST:event_jButtonBuscaMouseClicked

    private void jButtonDelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDelMouseClicked
        // TODO add your handling code here:
        int aux = Integer.parseInt(jTextFieldId.getText());
        ctrl.deletarCircuitoPorId(aux);
        Buscar(aux -1);
        jTextFieldId.setText(String.valueOf(aux-1));
        JOptionPane.showMessageDialog(this, "Circuito apagado do arquivo.");
    }//GEN-LAST:event_jButtonDelMouseClicked

    private void jButtonEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditMouseClicked
        // TODO add your handling code here:
        int aux = Integer.parseInt(jTextFieldId.getText());
        boolean er = false;
        Circuito circuito = new Circuito();
        circuito.setPista(jTextFieldPista.getText());
        circuito.setPais(jTextFieldPais.getText());
        circuito.setCidade(jTextFieldCidade.getText());
        circuito.setExtensao(Integer.parseInt(jTextFieldExt.getText()));
        circuito.setVoltas(Integer.parseInt(jTextFieldVoltas.getText()));
        circuito.setRecord(jTextFieldRcrd.getText());
        System.out.println(circuito.getId() + circuito.getPista() + circuito.getCidade());
        er = ctrl.editarCircuitoPorId(aux, circuito);
        if (er = true) {
            Buscar(aux);
            JOptionPane.showMessageDialog(this, "Circuito editado.");
        } else {
            JOptionPane.showMessageDialog(this, "Falha ao editar circuito.");
        }

    }//GEN-LAST:event_jButtonEditMouseClicked

    public void Nav(int index) {
        Circuito circuito = ctrl.getCircuitos().get(index);
        jTextFieldPista.setText(circuito.getPista());
        jTextFieldPais.setText(circuito.getPais());
        jTextFieldCidade.setText(circuito.getCidade());
        jTextFieldExt.setText(String.valueOf(circuito.getExtensao()));
        jTextFieldVoltas.setText(String.valueOf(circuito.getVoltas()));
        jTextFieldRcrd.setText(circuito.getRecord());
        jTextFieldId.setText(String.valueOf(circuito.getId()));
    }

    public void Buscar(int index) {
        Circuito circuito = ctrl.getCircuitoPorId(index);
        jTextFieldPista.setText(circuito.getPista());
        jTextFieldPais.setText(circuito.getPais());
        jTextFieldCidade.setText(circuito.getCidade());
        jTextFieldExt.setText(String.valueOf(circuito.getExtensao()));
        jTextFieldVoltas.setText(String.valueOf(circuito.getVoltas()));
        jTextFieldRcrd.setText(circuito.getRecord());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VwCircuito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VwCircuito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VwCircuito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VwCircuito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VwCircuito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbrir;
    private javax.swing.JButton jButtonAnt;
    private javax.swing.JButton jButtonBusca;
    private javax.swing.JButton jButtonDel;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonProx;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelExt;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelKm;
    private javax.swing.JLabel jLabelPais;
    private javax.swing.JLabel jLabelPista;
    private javax.swing.JLabel jLabelRcrd;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelVoltas;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldExt;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldPais;
    private javax.swing.JTextField jTextFieldPista;
    private javax.swing.JTextField jTextFieldRcrd;
    private javax.swing.JTextField jTextFieldVoltas;
    // End of variables declaration//GEN-END:variables
}
